language: php

stage: tests

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - composer remove --dev friendsofphp/php-cs-fixer vimeo/psalm
  - composer config --unset platform.php
  - composer update

script:
  - KINT_FILE=build/kint-js.phar php ./tests/basic.php
  - php ./tests/basic.php

stages:
  - analysis
  - tests

jobs:
  allow_failures:
    - php: nightly

  include:
    - php: 5.3
      dist: precise

    - php: nightly
      install:
        - composer remove --dev phpunit/phpunit friendsofphp/php-cs-fixer vimeo/psalm
        - composer require --dev phpunit/phpunit ^6

    # Check if `composer format` was run correctly
    - stage: analysis
      install: composer install
      script:
        - composer format
        - git status # Required to flush the cache
        - git diff-files --quiet --exit-code
      env: analysis_type="composer format"

    # Check if `composer build` was run correctly
    - stage: analysis
      install: composer install
      script:
        - composer clean
        # Travis is broken and screws with permissions. This breaks the build.
        # Instead we manually fix permissions before
        # building the phar file to ensure reproducibility.
        - chmod -R g-w .
        - composer build
        - git status # Required to flush the cache
        - git diff-files --quiet --exit-code
      env: analysis_type="composer build"

    # Check if code passes phpstan/psalm static analysis
    - stage: analysis
      install: composer install
      script: composer analyze
      env: analysis_type="composer analyze"

    # Preliminary test run
    - stage: analysis
      install: composer install
      script: php ./tests/basic.php
