language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.2
  - nightly

env: BUILD_TEST=false

# Add 7.1 with build testing and 5.2 with only
# basic testing. 5.1 isn't supported on TravisCI
matrix:
  include:
    - php: 7.1
      env: BUILD_TEST=true
    - php: 5.3
      dist: precise

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - phpenv config-rm xdebug.ini || return 0
  - if $BUILD_TEST; then composer install; else composer remove --dev friendsofphp/php-cs-fixer; fi

before_script:
  - phpenv global "$TRAVIS_PHP_VERSION"

script:
  - if $BUILD_TEST; then composer format && git status && git diff-files --quiet --exit-code; fi
  - php ./tests/basic.php
