language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env: BUILD_TEST=false

# Add 7.1 with build testing and 5.2 with only
# basic testing. 5.1 isn't supported on TravisCI
matrix:
  include:
    - php: 7.1
      env: BUILD_TEST=true
    - php: hhvm
      dist: trusty

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - phpenv global 7.1 || phpenv global 5.6 || return 0
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update 1.0.0
  - composer self-update
  - composer install

before_script:
  - phpenv global "$TRAVIS_PHP_VERSION"

script:
  - if $BUILD_TEST; then composer format && git status && git diff-files --quiet --exit-code; fi
  - php ./tests/basic.php
